language: node_js
node_js:
- '12.13'
install:
- npm install
- npm run build
before_deploy:
- npm install typescript@3.6 -g
after_deploy:
- npm publish
deploy:
  provider: npm
  email: hern.var@gmail.com
  api_key:
    secure: U4WBtv/HDA0T279kA6s8cQ/pmzP4dQPQ5vWZQKKik7PWuXwaeADb3foZrgJk3pCOEkdrI5B4/3FPI1Yixy4dzAboekv28/9DM3OUffGhFQTJvD83bCZ43ze9mkyA0Z2hPaUf7ySAQzJFKaGzPrixRanpKg4m7ZgE6jKepOHPj3GqpTW9kF4eu7Fai7FYVG2qy6VWrfAa9g5k9aCj0uYdnVux+OmwL6qUqEm1grobmcI7S9r0zQvmE3QFfk7s2u3xkrcSA1UDw9i1Ul5aGm6p7kSvpUB4547NxHeAFxLkbOWhZig5135d9ivztMRXYu/xJnNgAvQTlJ4PepEpf+zX6NNNZzdCNH8vCqkEaPb7xBVNtvqTEkOpkikRJZ3jShr9gzsdJCa2ISdQ4CiOHdfsGVVPaZ7QLOFh7Xx7Bnac3RhmUN54tBeLFNHJ1RxmFK29s2NC15RzIkngpR3oF2IBDl9AkhjyPqDQJcv8I5XXu+LFihDH30w0HOudc8vuhr2KaWthb1BCnBGfIqSq4zUs+WuDLoNnLukZYEL4zAH9d7S4JSDq3X9Bq8VQ8QDb0C4LWgWZozuTmqJxBNn8e85cc1So+bxl7z3kAh6CzRT2G10zJSyc6TAbZ5U9ttud/WWWm1YCqndP/ZNU/C6IeUrZl/GYuDPsUU+QBoYTIvEh16Y=
  skip_cleanup: true
  on:
    tags: true
    repo: mintproject/model-catalog-fetch-api-client
