language: node_js
node_js:
- '12.13'
install:
- npm install
- npm run build
before_deploy:
- npm install typescript@3.6 -g
deploy:
  provider: npm
  email: mosorio@isi.edu
  api_key:
    secure: YRsAeXjyLnd1doh83n33nDGRv4ey57U43haD3w51pqPKZ4hUgoKyFWCaCbVF7gy1vd6uTyZ/Z8cnJrqXDGWWVKI4XTIm0TkEWFyoZsV7t+4cKen3RcgL43WzM2sPg54ON5CZk9+w57VrWUN92ZcCOWFmXGKdTsz+n+g4Pnb2egh1sjiXWSQ4ztCNYy/xD8puxUmSeOhroGzr+BviTevm77n1j0S1DfuWKBiHhL62ZWZ/j4RGYGpFF4Go91PYtl5GYKIc9pImDi87xlso9OX23s31xB7c4OZNSw2LIAWv40MWm9Yt4b8ohhHqobP+mtzlcjVmiR14Sr3xBmTY+3rIri4CSlyz2LIl5dxYL5HfeJALrPC2fWNLM0iWLxdCCwgGqkVhvE7qavSE59Ox9YwrLm9mc2Mc4iy+as5voKgqSo33B8rnF1X1rUcX2N5l/yItBgmzkGDJ4KFl9V89dC716j/8cF8deN/NYRJsru050I7YHzRIL4XKJYHbExV5yKj8TWM2a6UZhZt3nvtegvdl8GFoId0+otq+rcTz+dWi6hiWJVntL/yWsZAA56tU3zNMdqBZV4YQpjzE4tubLU3l/4CrCyaSKi/Cewooxe8kkc2gWHyGohwkvFlt5+r0WUjZmsb7zU1+f1QhqD4SC61MxTQsbMFTTObKNYfo02EMvGI=
  skip_cleanup: true
