// tslint:disable
/**
 * Model Catalog
 * This is the API of the Software Description Ontology at [https://w3id.org/okn/o/sdm](https://w3id.org/okn/o/sdm)
 *
 * The version of the OpenAPI document: v1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CatalogIdentifier,
    CatalogIdentifierFromJSON,
    CatalogIdentifierToJSON,
} from '../models';

export interface CatalogidentifiersGetRequest {
    username?: string;
    label?: string;
    page?: number;
    perPage?: number;
}

export interface CatalogidentifiersIdDeleteRequest {
    id: string;
    user?: string;
}

export interface CatalogidentifiersIdGetRequest {
    id: string;
    username?: string;
}

export interface CatalogidentifiersIdPutRequest {
    id: string;
    user?: string;
    catalogIdentifier?: CatalogIdentifier;
}

export interface CatalogidentifiersPostRequest {
    user?: string;
    catalogIdentifier?: CatalogIdentifier;
}

/**
 * no description
 */
export class CatalogIdentifierApi extends runtime.BaseAPI {

    /**
     * Gets a list of all instances of CatalogIdentifier (more information in https://w3id.org/okn/o/sd#CatalogIdentifier)
     * List all instances of CatalogIdentifier
     */
    async catalogidentifiersGetRaw(requestParameters: CatalogidentifiersGetRequest): Promise<runtime.ApiResponse<Array<CatalogIdentifier>>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.username !== undefined) {
            queryParameters['username'] = requestParameters.username;
        }

        if (requestParameters.label !== undefined) {
            queryParameters['label'] = requestParameters.label;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.perPage !== undefined) {
            queryParameters['per_page'] = requestParameters.perPage;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/catalogidentifiers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CatalogIdentifierFromJSON));
    }

   /**
    * Gets a list of all instances of CatalogIdentifier (more information in https://w3id.org/okn/o/sd#CatalogIdentifier)
    * List all instances of CatalogIdentifier
    */
    async catalogidentifiersGet(requestParameters: CatalogidentifiersGetRequest): Promise<Array<CatalogIdentifier>> {
        const response = await this.catalogidentifiersGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * Delete an existing CatalogIdentifier (more information in https://w3id.org/okn/o/sd#CatalogIdentifier)
     * Delete an existing CatalogIdentifier
     */
    async catalogidentifiersIdDeleteRaw(requestParameters: CatalogidentifiersIdDeleteRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling catalogidentifiersIdDelete.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.user !== undefined) {
            queryParameters['user'] = requestParameters.user;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("BearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/catalogidentifiers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

   /**
    * Delete an existing CatalogIdentifier (more information in https://w3id.org/okn/o/sd#CatalogIdentifier)
    * Delete an existing CatalogIdentifier
    */
    async catalogidentifiersIdDelete(requestParameters: CatalogidentifiersIdDeleteRequest): Promise<void> {
        await this.catalogidentifiersIdDeleteRaw(requestParameters);
    }

    /**
     * Gets the details of a given CatalogIdentifier (more information in https://w3id.org/okn/o/sd#CatalogIdentifier)
     * Get a single CatalogIdentifier by its id
     */
    async catalogidentifiersIdGetRaw(requestParameters: CatalogidentifiersIdGetRequest): Promise<runtime.ApiResponse<CatalogIdentifier>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling catalogidentifiersIdGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.username !== undefined) {
            queryParameters['username'] = requestParameters.username;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/catalogidentifiers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => CatalogIdentifierFromJSON(jsonValue));
    }

   /**
    * Gets the details of a given CatalogIdentifier (more information in https://w3id.org/okn/o/sd#CatalogIdentifier)
    * Get a single CatalogIdentifier by its id
    */
    async catalogidentifiersIdGet(requestParameters: CatalogidentifiersIdGetRequest): Promise<CatalogIdentifier> {
        const response = await this.catalogidentifiersIdGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * Updates an existing CatalogIdentifier (more information in https://w3id.org/okn/o/sd#CatalogIdentifier)
     * Update an existing CatalogIdentifier
     */
    async catalogidentifiersIdPutRaw(requestParameters: CatalogidentifiersIdPutRequest): Promise<runtime.ApiResponse<CatalogIdentifier>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling catalogidentifiersIdPut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.user !== undefined) {
            queryParameters['user'] = requestParameters.user;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("BearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/catalogidentifiers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CatalogIdentifierToJSON(requestParameters.catalogIdentifier),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => CatalogIdentifierFromJSON(jsonValue));
    }

   /**
    * Updates an existing CatalogIdentifier (more information in https://w3id.org/okn/o/sd#CatalogIdentifier)
    * Update an existing CatalogIdentifier
    */
    async catalogidentifiersIdPut(requestParameters: CatalogidentifiersIdPutRequest): Promise<CatalogIdentifier> {
        const response = await this.catalogidentifiersIdPutRaw(requestParameters);
        return await response.value();
    }

    /**
     * Create a new instance of CatalogIdentifier (more information in https://w3id.org/okn/o/sd#CatalogIdentifier)
     * Create one CatalogIdentifier
     */
    async catalogidentifiersPostRaw(requestParameters: CatalogidentifiersPostRequest): Promise<runtime.ApiResponse<CatalogIdentifier>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.user !== undefined) {
            queryParameters['user'] = requestParameters.user;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("BearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/catalogidentifiers`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CatalogIdentifierToJSON(requestParameters.catalogIdentifier),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => CatalogIdentifierFromJSON(jsonValue));
    }

   /**
    * Create a new instance of CatalogIdentifier (more information in https://w3id.org/okn/o/sd#CatalogIdentifier)
    * Create one CatalogIdentifier
    */
    async catalogidentifiersPost(requestParameters: CatalogidentifiersPostRequest): Promise<CatalogIdentifier> {
        const response = await this.catalogidentifiersPostRaw(requestParameters);
        return await response.value();
    }

}
