// tslint:disable
/**
 * Model Catalog
 * This is the API of the Software Description Ontology at [https://w3id.org/okn/o/sdm](https://w3id.org/okn/o/sdm)
 *
 * The version of the OpenAPI document: v1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    User,
    UserFromJSON,
    UserToJSON,
} from '../models';

export interface UserLoginPostRequest {
    user?: User;
}

/**
 * no description
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Login the user
     */
    async userLoginPostRaw(requestParameters: UserLoginPostRequest): Promise<runtime.ApiResponse<string>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserToJSON(requestParameters.user),
        });

        return new runtime.TextApiResponse(response);
    }

   /**
    * Login the user
    */
    async userLoginPost(requestParameters: UserLoginPostRequest): Promise<string> {
        const response = await this.userLoginPostRaw(requestParameters);
        return await response.value();
    }

}
