// tslint:disable
/**
 * Model Catalog
 * This is the API of the Software Description Ontology at [https://w3id.org/okn/o/sdm](https://w3id.org/okn/o/sdm)
 *
 * The version of the OpenAPI document: v1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ModelConfiguration,
    ModelConfigurationFromJSON,
    ModelConfigurationToJSON,
} from '../models';

export interface CustomModelconfigurationsIdGetRequest {
    id: string;
    username?: string;
    customQueryName?: string;
}

export interface ModelconfigurationsGetRequest {
    username?: string;
    label?: string;
    page?: number;
    perPage?: number;
}

export interface ModelconfigurationsIdDeleteRequest {
    id: string;
    user?: string;
}

export interface ModelconfigurationsIdGetRequest {
    id: string;
    username?: string;
}

export interface ModelconfigurationsIdPutRequest {
    id: string;
    user?: string;
    modelConfiguration?: ModelConfiguration;
}

export interface ModelconfigurationsPostRequest {
    user?: string;
    modelConfiguration?: ModelConfiguration;
}

/**
 * no description
 */
export class ModelConfigurationApi extends runtime.BaseAPI {

    /**
     * Gets the details of a single instance of a ModelConfiguration
     * Get a ModelConfiguration
     */
    async customModelconfigurationsIdGetRaw(requestParameters: CustomModelconfigurationsIdGetRequest): Promise<runtime.ApiResponse<ModelConfiguration>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling customModelconfigurationsIdGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.username !== undefined) {
            queryParameters['username'] = requestParameters.username;
        }

        if (requestParameters.customQueryName !== undefined) {
            queryParameters['custom_query_name'] = requestParameters.customQueryName;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/custom/modelconfigurations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelConfigurationFromJSON(jsonValue));
    }

   /**
    * Gets the details of a single instance of a ModelConfiguration
    * Get a ModelConfiguration
    */
    async customModelconfigurationsIdGet(requestParameters: CustomModelconfigurationsIdGetRequest): Promise<ModelConfiguration> {
        const response = await this.customModelconfigurationsIdGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * Gets a list of all instances of ModelConfiguration (more information in https://w3id.org/okn/o/sdm#ModelConfiguration)
     * List all instances of ModelConfiguration
     */
    async modelconfigurationsGetRaw(requestParameters: ModelconfigurationsGetRequest): Promise<runtime.ApiResponse<Array<ModelConfiguration>>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.username !== undefined) {
            queryParameters['username'] = requestParameters.username;
        }

        if (requestParameters.label !== undefined) {
            queryParameters['label'] = requestParameters.label;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.perPage !== undefined) {
            queryParameters['per_page'] = requestParameters.perPage;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/modelconfigurations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ModelConfigurationFromJSON));
    }

   /**
    * Gets a list of all instances of ModelConfiguration (more information in https://w3id.org/okn/o/sdm#ModelConfiguration)
    * List all instances of ModelConfiguration
    */
    async modelconfigurationsGet(requestParameters: ModelconfigurationsGetRequest): Promise<Array<ModelConfiguration>> {
        const response = await this.modelconfigurationsGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * Delete an existing ModelConfiguration (more information in https://w3id.org/okn/o/sdm#ModelConfiguration)
     * Delete an existing ModelConfiguration
     */
    async modelconfigurationsIdDeleteRaw(requestParameters: ModelconfigurationsIdDeleteRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling modelconfigurationsIdDelete.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.user !== undefined) {
            queryParameters['user'] = requestParameters.user;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("BearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/modelconfigurations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

   /**
    * Delete an existing ModelConfiguration (more information in https://w3id.org/okn/o/sdm#ModelConfiguration)
    * Delete an existing ModelConfiguration
    */
    async modelconfigurationsIdDelete(requestParameters: ModelconfigurationsIdDeleteRequest): Promise<void> {
        await this.modelconfigurationsIdDeleteRaw(requestParameters);
    }

    /**
     * Gets the details of a given ModelConfiguration (more information in https://w3id.org/okn/o/sdm#ModelConfiguration)
     * Get a single ModelConfiguration by its id
     */
    async modelconfigurationsIdGetRaw(requestParameters: ModelconfigurationsIdGetRequest): Promise<runtime.ApiResponse<ModelConfiguration>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling modelconfigurationsIdGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.username !== undefined) {
            queryParameters['username'] = requestParameters.username;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/modelconfigurations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelConfigurationFromJSON(jsonValue));
    }

   /**
    * Gets the details of a given ModelConfiguration (more information in https://w3id.org/okn/o/sdm#ModelConfiguration)
    * Get a single ModelConfiguration by its id
    */
    async modelconfigurationsIdGet(requestParameters: ModelconfigurationsIdGetRequest): Promise<ModelConfiguration> {
        const response = await this.modelconfigurationsIdGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * Updates an existing ModelConfiguration (more information in https://w3id.org/okn/o/sdm#ModelConfiguration)
     * Update an existing ModelConfiguration
     */
    async modelconfigurationsIdPutRaw(requestParameters: ModelconfigurationsIdPutRequest): Promise<runtime.ApiResponse<ModelConfiguration>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling modelconfigurationsIdPut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.user !== undefined) {
            queryParameters['user'] = requestParameters.user;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("BearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/modelconfigurations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ModelConfigurationToJSON(requestParameters.modelConfiguration),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelConfigurationFromJSON(jsonValue));
    }

   /**
    * Updates an existing ModelConfiguration (more information in https://w3id.org/okn/o/sdm#ModelConfiguration)
    * Update an existing ModelConfiguration
    */
    async modelconfigurationsIdPut(requestParameters: ModelconfigurationsIdPutRequest): Promise<ModelConfiguration> {
        const response = await this.modelconfigurationsIdPutRaw(requestParameters);
        return await response.value();
    }

    /**
     * Create a new instance of ModelConfiguration (more information in https://w3id.org/okn/o/sdm#ModelConfiguration)
     * Create one ModelConfiguration
     */
    async modelconfigurationsPostRaw(requestParameters: ModelconfigurationsPostRequest): Promise<runtime.ApiResponse<ModelConfiguration>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.user !== undefined) {
            queryParameters['user'] = requestParameters.user;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("BearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/modelconfigurations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModelConfigurationToJSON(requestParameters.modelConfiguration),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelConfigurationFromJSON(jsonValue));
    }

   /**
    * Create a new instance of ModelConfiguration (more information in https://w3id.org/okn/o/sdm#ModelConfiguration)
    * Create one ModelConfiguration
    */
    async modelconfigurationsPost(requestParameters: ModelconfigurationsPostRequest): Promise<ModelConfiguration> {
        const response = await this.modelconfigurationsPostRaw(requestParameters);
        return await response.value();
    }

}
