// tslint:disable
/**
 * Model Catalog
 * This is the API of the Software Description Ontology at [https://w3id.org/okn/o/sdm](https://w3id.org/okn/o/sdm)
 *
 * The version of the OpenAPI document: v1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Parameter,
    ParameterFromJSON,
    ParameterToJSON,
} from '../models';

export interface ParametersGetRequest {
    username?: string;
    label?: string;
    page?: number;
    perPage?: number;
}

export interface ParametersIdDeleteRequest {
    id: string;
    user: string;
}

export interface ParametersIdGetRequest {
    id: string;
    username?: string;
}

export interface ParametersIdPutRequest {
    id: string;
    user: string;
    parameter?: Parameter;
}

export interface ParametersPostRequest {
    user: string;
    parameter?: Parameter;
}

/**
 * no description
 */
export class ParameterApi extends runtime.BaseAPI {

    /**
     * Gets a list of all instances of Parameter (more information in https://w3id.org/okn/o/sd#Parameter)
     * List all instances of Parameter
     */
    async parametersGetRaw(requestParameters: ParametersGetRequest): Promise<runtime.ApiResponse<Array<Parameter>>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.username !== undefined) {
            queryParameters['username'] = requestParameters.username;
        }

        if (requestParameters.label !== undefined) {
            queryParameters['label'] = requestParameters.label;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.perPage !== undefined) {
            queryParameters['per_page'] = requestParameters.perPage;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/parameters`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ParameterFromJSON));
    }

   /**
    * Gets a list of all instances of Parameter (more information in https://w3id.org/okn/o/sd#Parameter)
    * List all instances of Parameter
    */
    async parametersGet(requestParameters: ParametersGetRequest): Promise<Array<Parameter>> {
        const response = await this.parametersGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * Delete an existing Parameter (more information in https://w3id.org/okn/o/sd#Parameter)
     * Delete an existing Parameter
     */
    async parametersIdDeleteRaw(requestParameters: ParametersIdDeleteRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling parametersIdDelete.');
        }

        if (requestParameters.user === null || requestParameters.user === undefined) {
            throw new runtime.RequiredError('user','Required parameter requestParameters.user was null or undefined when calling parametersIdDelete.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("BearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/parameters/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))).replace(`{${"user"}}`, encodeURIComponent(String(requestParameters.user))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

   /**
    * Delete an existing Parameter (more information in https://w3id.org/okn/o/sd#Parameter)
    * Delete an existing Parameter
    */
    async parametersIdDelete(requestParameters: ParametersIdDeleteRequest): Promise<void> {
        await this.parametersIdDeleteRaw(requestParameters);
    }

    /**
     * Gets the details of a given Parameter (more information in https://w3id.org/okn/o/sd#Parameter)
     * Get a single Parameter by its id
     */
    async parametersIdGetRaw(requestParameters: ParametersIdGetRequest): Promise<runtime.ApiResponse<Parameter>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling parametersIdGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.username !== undefined) {
            queryParameters['username'] = requestParameters.username;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/parameters/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ParameterFromJSON(jsonValue));
    }

   /**
    * Gets the details of a given Parameter (more information in https://w3id.org/okn/o/sd#Parameter)
    * Get a single Parameter by its id
    */
    async parametersIdGet(requestParameters: ParametersIdGetRequest): Promise<Parameter> {
        const response = await this.parametersIdGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * Updates an existing Parameter (more information in https://w3id.org/okn/o/sd#Parameter)
     * Update an existing Parameter
     */
    async parametersIdPutRaw(requestParameters: ParametersIdPutRequest): Promise<runtime.ApiResponse<Parameter>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling parametersIdPut.');
        }

        if (requestParameters.user === null || requestParameters.user === undefined) {
            throw new runtime.RequiredError('user','Required parameter requestParameters.user was null or undefined when calling parametersIdPut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("BearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/parameters/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))).replace(`{${"user"}}`, encodeURIComponent(String(requestParameters.user))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ParameterToJSON(requestParameters.parameter),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ParameterFromJSON(jsonValue));
    }

   /**
    * Updates an existing Parameter (more information in https://w3id.org/okn/o/sd#Parameter)
    * Update an existing Parameter
    */
    async parametersIdPut(requestParameters: ParametersIdPutRequest): Promise<Parameter> {
        const response = await this.parametersIdPutRaw(requestParameters);
        return await response.value();
    }

    /**
     * Create a new instance of Parameter (more information in https://w3id.org/okn/o/sd#Parameter)
     * Create one Parameter
     */
    async parametersPostRaw(requestParameters: ParametersPostRequest): Promise<runtime.ApiResponse<Parameter>> {
        if (requestParameters.user === null || requestParameters.user === undefined) {
            throw new runtime.RequiredError('user','Required parameter requestParameters.user was null or undefined when calling parametersPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("BearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/parameters`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters.user))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ParameterToJSON(requestParameters.parameter),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ParameterFromJSON(jsonValue));
    }

   /**
    * Create a new instance of Parameter (more information in https://w3id.org/okn/o/sd#Parameter)
    * Create one Parameter
    */
    async parametersPost(requestParameters: ParametersPostRequest): Promise<Parameter> {
        const response = await this.parametersPostRaw(requestParameters);
        return await response.value();
    }

}
