// tslint:disable
/**
 * Model Catalog
 * This is MINT Model Catalog You can find out more about Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    SampleResource,
    SampleResourceFromJSON,
    SampleResourceToJSON,
} from '../models';

export interface SampleresourcesGetRequest {
    username?: string;
    queryText?: string;
}

export interface SampleresourcesIdDeleteRequest {
    id: string;
    user: string;
}

export interface SampleresourcesIdGetRequest {
    id: string;
    username?: string;
}

export interface SampleresourcesIdPutRequest {
    id: string;
    user: string;
    sampleResource?: SampleResource;
}

export interface SampleresourcesPostRequest {
    user: string;
    sampleResource?: SampleResource;
}

/**
 * no description
 */
export class SampleResourceApi extends runtime.BaseAPI {

    /**
     * Gets a list of all SampleResource entities
     * List all SampleResource entities
     */
    async sampleresourcesGetRaw(requestParameters: SampleresourcesGetRequest): Promise<runtime.ApiResponse<Array<SampleResource>>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.username !== undefined) {
            queryParameters['username'] = requestParameters.username;
        }

        if (requestParameters.queryText !== undefined) {
            queryParameters['query_text'] = requestParameters.queryText;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sampleresources`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SampleResourceFromJSON));
    }

   /**
    * Gets a list of all SampleResource entities
    * List all SampleResource entities
    */
    async sampleresourcesGet(requestParameters: SampleresourcesGetRequest): Promise<Array<SampleResource>> {
        const response = await this.sampleresourcesGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * Delete an existing SampleResource
     * Delete a SampleResource
     */
    async sampleresourcesIdDeleteRaw(requestParameters: SampleresourcesIdDeleteRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling sampleresourcesIdDelete.');
        }

        if (requestParameters.user === null || requestParameters.user === undefined) {
            throw new runtime.RequiredError('user','Required parameter requestParameters.user was null or undefined when calling sampleresourcesIdDelete.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("BearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/sampleresources/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))).replace(`{${"user"}}`, encodeURIComponent(String(requestParameters.user))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

   /**
    * Delete an existing SampleResource
    * Delete a SampleResource
    */
    async sampleresourcesIdDelete(requestParameters: SampleresourcesIdDeleteRequest): Promise<void> {
        await this.sampleresourcesIdDeleteRaw(requestParameters);
    }

    /**
     * Gets the details of a single instance of a SampleResource
     * Get a SampleResource
     */
    async sampleresourcesIdGetRaw(requestParameters: SampleresourcesIdGetRequest): Promise<runtime.ApiResponse<SampleResource>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling sampleresourcesIdGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.username !== undefined) {
            queryParameters['username'] = requestParameters.username;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sampleresources/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => SampleResourceFromJSON(jsonValue));
    }

   /**
    * Gets the details of a single instance of a SampleResource
    * Get a SampleResource
    */
    async sampleresourcesIdGet(requestParameters: SampleresourcesIdGetRequest): Promise<SampleResource> {
        const response = await this.sampleresourcesIdGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * Updates an existing SampleResource
     * Update a SampleResource
     */
    async sampleresourcesIdPutRaw(requestParameters: SampleresourcesIdPutRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling sampleresourcesIdPut.');
        }

        if (requestParameters.user === null || requestParameters.user === undefined) {
            throw new runtime.RequiredError('user','Required parameter requestParameters.user was null or undefined when calling sampleresourcesIdPut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("BearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/sampleresources/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))).replace(`{${"user"}}`, encodeURIComponent(String(requestParameters.user))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SampleResourceToJSON(requestParameters.sampleResource),
        });

        return new runtime.VoidApiResponse(response);
    }

   /**
    * Updates an existing SampleResource
    * Update a SampleResource
    */
    async sampleresourcesIdPut(requestParameters: SampleresourcesIdPutRequest): Promise<void> {
        await this.sampleresourcesIdPutRaw(requestParameters);
    }

    /**
     * Create a new instance of a SampleResource
     * Create a SampleResource
     */
    async sampleresourcesPostRaw(requestParameters: SampleresourcesPostRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.user === null || requestParameters.user === undefined) {
            throw new runtime.RequiredError('user','Required parameter requestParameters.user was null or undefined when calling sampleresourcesPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("BearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/sampleresources`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters.user))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SampleResourceToJSON(requestParameters.sampleResource),
        });

        return new runtime.VoidApiResponse(response);
    }

   /**
    * Create a new instance of a SampleResource
    * Create a SampleResource
    */
    async sampleresourcesPost(requestParameters: SampleresourcesPostRequest): Promise<void> {
        await this.sampleresourcesPostRaw(requestParameters);
    }

}
