// tslint:disable
/**
 * Model Catalog
 * This is MINT Model Catalog You can find out more about Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)
 *
 * The version of the OpenAPI document: v1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    SpatialResolution,
    SpatialResolutionFromJSON,
    SpatialResolutionToJSON,
} from '../models';

export interface SpatialresolutionsGetRequest {
    username?: string;
    label?: string;
}

export interface SpatialresolutionsIdDeleteRequest {
    id: string;
    user: string;
}

export interface SpatialresolutionsIdGetRequest {
    id: string;
    username?: string;
}

export interface SpatialresolutionsIdPutRequest {
    id: string;
    user: string;
    spatialResolution?: SpatialResolution;
}

export interface SpatialresolutionsPostRequest {
    user: string;
    spatialResolution?: SpatialResolution;
}

/**
 * no description
 */
export class SpatialResolutionApi extends runtime.BaseAPI {

    /**
     * Gets a list of all SpatialResolution entities
     * List all SpatialResolution entities
     */
    async spatialresolutionsGetRaw(requestParameters: SpatialresolutionsGetRequest): Promise<runtime.ApiResponse<Array<SpatialResolution>>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.username !== undefined) {
            queryParameters['username'] = requestParameters.username;
        }

        if (requestParameters.label !== undefined) {
            queryParameters['label'] = requestParameters.label;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/spatialresolutions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SpatialResolutionFromJSON));
    }

   /**
    * Gets a list of all SpatialResolution entities
    * List all SpatialResolution entities
    */
    async spatialresolutionsGet(requestParameters: SpatialresolutionsGetRequest): Promise<Array<SpatialResolution>> {
        const response = await this.spatialresolutionsGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * Delete an existing SpatialResolution
     * Delete a SpatialResolution
     */
    async spatialresolutionsIdDeleteRaw(requestParameters: SpatialresolutionsIdDeleteRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling spatialresolutionsIdDelete.');
        }

        if (requestParameters.user === null || requestParameters.user === undefined) {
            throw new runtime.RequiredError('user','Required parameter requestParameters.user was null or undefined when calling spatialresolutionsIdDelete.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("BearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/spatialresolutions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))).replace(`{${"user"}}`, encodeURIComponent(String(requestParameters.user))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

   /**
    * Delete an existing SpatialResolution
    * Delete a SpatialResolution
    */
    async spatialresolutionsIdDelete(requestParameters: SpatialresolutionsIdDeleteRequest): Promise<void> {
        await this.spatialresolutionsIdDeleteRaw(requestParameters);
    }

    /**
     * Gets the details of a single instance of a SpatialResolution
     * Get a SpatialResolution
     */
    async spatialresolutionsIdGetRaw(requestParameters: SpatialresolutionsIdGetRequest): Promise<runtime.ApiResponse<SpatialResolution>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling spatialresolutionsIdGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.username !== undefined) {
            queryParameters['username'] = requestParameters.username;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/spatialresolutions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => SpatialResolutionFromJSON(jsonValue));
    }

   /**
    * Gets the details of a single instance of a SpatialResolution
    * Get a SpatialResolution
    */
    async spatialresolutionsIdGet(requestParameters: SpatialresolutionsIdGetRequest): Promise<SpatialResolution> {
        const response = await this.spatialresolutionsIdGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * Updates an existing SpatialResolution
     * Update a SpatialResolution
     */
    async spatialresolutionsIdPutRaw(requestParameters: SpatialresolutionsIdPutRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling spatialresolutionsIdPut.');
        }

        if (requestParameters.user === null || requestParameters.user === undefined) {
            throw new runtime.RequiredError('user','Required parameter requestParameters.user was null or undefined when calling spatialresolutionsIdPut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("BearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/spatialresolutions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))).replace(`{${"user"}}`, encodeURIComponent(String(requestParameters.user))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SpatialResolutionToJSON(requestParameters.spatialResolution),
        });

        return new runtime.VoidApiResponse(response);
    }

   /**
    * Updates an existing SpatialResolution
    * Update a SpatialResolution
    */
    async spatialresolutionsIdPut(requestParameters: SpatialresolutionsIdPutRequest): Promise<void> {
        await this.spatialresolutionsIdPutRaw(requestParameters);
    }

    /**
     * Create a new instance of a SpatialResolution
     * Create a SpatialResolution
     */
    async spatialresolutionsPostRaw(requestParameters: SpatialresolutionsPostRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.user === null || requestParameters.user === undefined) {
            throw new runtime.RequiredError('user','Required parameter requestParameters.user was null or undefined when calling spatialresolutionsPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("BearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/spatialresolutions`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters.user))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SpatialResolutionToJSON(requestParameters.spatialResolution),
        });

        return new runtime.VoidApiResponse(response);
    }

   /**
    * Create a new instance of a SpatialResolution
    * Create a SpatialResolution
    */
    async spatialresolutionsPost(requestParameters: SpatialresolutionsPostRequest): Promise<void> {
        await this.spatialresolutionsPostRaw(requestParameters);
    }

}
