// tslint:disable
/**
 * Model Catalog
 * This is the API of the  Software Description Ontology at [https://mintproject.github.io/Mint-ModelCatalog-Ontology/release/1.2.0/index-en.html](https://w3id.org/okn/o/sdm)
 *
 * The version of the OpenAPI document: v1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CausalDiagram
 */
export interface CausalDiagram {
    /**
     * 
     * @type {Array<string>}
     * @memberof CausalDiagram
     */
    description?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof CausalDiagram
     */
    id?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CausalDiagram
     */
    label?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CausalDiagram
     */
    type?: Array<string> | null;
    /**
     * 
     * @type {Array<object>}
     * @memberof CausalDiagram
     */
    hasPart?: Array<object> | null;
}

export function CausalDiagramFromJSON(json: any): CausalDiagram {
    return CausalDiagramFromJSONTyped(json, false);
}

export function CausalDiagramFromJSONTyped(json: any, ignoreDiscriminator: boolean): CausalDiagram {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'hasPart': !exists(json, 'hasPart') ? undefined : json['hasPart'],
    };
}

export function CausalDiagramToJSON(value?: CausalDiagram): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'id': value.id,
        'label': value.label,
        'type': value.type,
        'hasPart': value.hasPart,
    };
}


