// tslint:disable
/**
 * Model Catalog
 * This is the API of the Software Description Ontology at [https://w3id.org/okn/o/sdm](https://w3id.org/okn/o/sdm)
 *
 * The version of the OpenAPI document: v1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Any interventions that affects farming practices
 * @export
 * @interface FarmingPractices
 */
export interface FarmingPractices {
    /**
     * small description
     * @type {Array<string>}
     * @memberof FarmingPractices
     */
    description?: Array<string> | null;
    /**
     * identifier
     * @type {string}
     * @memberof FarmingPractices
     */
    id?: string;
    /**
     * short description of the resource
     * @type {Array<string>}
     * @memberof FarmingPractices
     */
    label?: Array<string> | null;
    /**
     * type of the resource
     * @type {Array<string>}
     * @memberof FarmingPractices
     */
    type?: Array<string> | null;
}

export function FarmingPracticesFromJSON(json: any): FarmingPractices {
    return FarmingPracticesFromJSONTyped(json, false);
}

export function FarmingPracticesFromJSONTyped(json: any, ignoreDiscriminator: boolean): FarmingPractices {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function FarmingPracticesToJSON(value?: FarmingPractices): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'id': value.id,
        'label': value.label,
        'type': value.type,
    };
}


