// tslint:disable
/**
 * Model Catalog
 * This is the API of the  Software Description Ontology at [https://mintproject.github.io/Mint-ModelCatalog-Ontology/release/1.2.0/index-en.html](https://w3id.org/okn/o/sdm)
 *
 * The version of the OpenAPI document: v1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeoCoordinates
 */
export interface GeoCoordinates {
    /**
     * 
     * @type {Array<string>}
     * @memberof GeoCoordinates
     */
    elevation?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof GeoCoordinates
     */
    latitude?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof GeoCoordinates
     */
    description?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof GeoCoordinates
     */
    id?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GeoCoordinates
     */
    label?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof GeoCoordinates
     */
    type?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof GeoCoordinates
     */
    longitude?: Array<string> | null;
}

export function GeoCoordinatesFromJSON(json: any): GeoCoordinates {
    return GeoCoordinatesFromJSONTyped(json, false);
}

export function GeoCoordinatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoCoordinates {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'elevation': !exists(json, 'elevation') ? undefined : json['elevation'],
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
    };
}

export function GeoCoordinatesToJSON(value?: GeoCoordinates): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'elevation': value.elevation,
        'latitude': value.latitude,
        'description': value.description,
        'id': value.id,
        'label': value.label,
        'type': value.type,
        'longitude': value.longitude,
    };
}


