// tslint:disable
/**
 * Model Catalog
 * This is the API of the  Software Description Ontology at [https://w3id.org/okn/o/sdm](https://w3id.org/okn/o/sdm)
 *
 * The version of the OpenAPI document: v1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Intervention,
    InterventionFromJSON,
    InterventionFromJSONTyped,
    InterventionToJSON,
    Unit,
    UnitFromJSON,
    UnitFromJSONTyped,
    UnitToJSON,
    Variable,
    VariableFromJSON,
    VariableFromJSONTyped,
    VariableToJSON,
    VariablePresentation,
    VariablePresentationFromJSON,
    VariablePresentationFromJSONTyped,
    VariablePresentationToJSON,
} from './';

/**
 * 
 * @export
 * @interface Parameter
 */
export interface Parameter {
    /**
     * 
     * @type {Array<object>}
     * @memberof Parameter
     */
    hasDefaultValue?: Array<object> | null;
    /**
     * 
     * @type {Array<object>}
     * @memberof Parameter
     */
    hasMaximumAcceptedValue?: Array<object> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Parameter
     */
    description?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Parameter
     */
    hasDataType?: Array<string> | null;
    /**
     * 
     * @type {Array<object>}
     * @memberof Parameter
     */
    hasFixedValue?: Array<object> | null;
    /**
     * 
     * @type {Array<VariablePresentation>}
     * @memberof Parameter
     */
    hasPresentation?: Array<VariablePresentation> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Parameter
     */
    label?: Array<string> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof Parameter
     */
    recommendedIncrement?: Array<number> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Parameter
     */
    type?: Array<string> | null;
    /**
     * 
     * @type {Array<object>}
     * @memberof Parameter
     */
    hasMinimumAcceptedValue?: Array<object> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Parameter
     */
    hasAcceptedValues?: Array<string> | null;
    /**
     * 
     * @type {Array<Variable>}
     * @memberof Parameter
     */
    adjustsVariable?: Array<Variable> | null;
    /**
     * 
     * @type {Array<Intervention>}
     * @memberof Parameter
     */
    relevantForIntervention?: Array<Intervention> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof Parameter
     */
    position?: Array<number> | null;
    /**
     * 
     * @type {string}
     * @memberof Parameter
     */
    id?: string;
    /**
     * 
     * @type {Array<Unit>}
     * @memberof Parameter
     */
    usesUnit?: Array<Unit> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof Parameter
     */
    hasStepSize?: Array<number> | null;
}

export function ParameterFromJSON(json: any): Parameter {
    return ParameterFromJSONTyped(json, false);
}

export function ParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Parameter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hasDefaultValue': !exists(json, 'hasDefaultValue') ? undefined : json['hasDefaultValue'],
        'hasMaximumAcceptedValue': !exists(json, 'hasMaximumAcceptedValue') ? undefined : json['hasMaximumAcceptedValue'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'hasDataType': !exists(json, 'hasDataType') ? undefined : json['hasDataType'],
        'hasFixedValue': !exists(json, 'hasFixedValue') ? undefined : json['hasFixedValue'],
        'hasPresentation': !exists(json, 'hasPresentation') ? undefined : (json['hasPresentation'] as Array<any>).map(VariablePresentationFromJSON),
        'label': !exists(json, 'label') ? undefined : json['label'],
        'recommendedIncrement': !exists(json, 'recommendedIncrement') ? undefined : json['recommendedIncrement'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'hasMinimumAcceptedValue': !exists(json, 'hasMinimumAcceptedValue') ? undefined : json['hasMinimumAcceptedValue'],
        'hasAcceptedValues': !exists(json, 'hasAcceptedValues') ? undefined : json['hasAcceptedValues'],
        'adjustsVariable': !exists(json, 'adjustsVariable') ? undefined : (json['adjustsVariable'] as Array<any>).map(VariableFromJSON),
        'relevantForIntervention': !exists(json, 'relevantForIntervention') ? undefined : (json['relevantForIntervention'] as Array<any>).map(InterventionFromJSON),
        'position': !exists(json, 'position') ? undefined : json['position'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'usesUnit': !exists(json, 'usesUnit') ? undefined : (json['usesUnit'] as Array<any>).map(UnitFromJSON),
        'hasStepSize': !exists(json, 'hasStepSize') ? undefined : json['hasStepSize'],
    };
}

export function ParameterToJSON(value?: Parameter): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hasDefaultValue': value.hasDefaultValue,
        'hasMaximumAcceptedValue': value.hasMaximumAcceptedValue,
        'description': value.description,
        'hasDataType': value.hasDataType,
        'hasFixedValue': value.hasFixedValue,
        'hasPresentation': value.hasPresentation === undefined ? undefined : (value.hasPresentation as Array<any>).map(VariablePresentationToJSON),
        'label': value.label,
        'recommendedIncrement': value.recommendedIncrement,
        'type': value.type,
        'hasMinimumAcceptedValue': value.hasMinimumAcceptedValue,
        'hasAcceptedValues': value.hasAcceptedValues,
        'adjustsVariable': value.adjustsVariable === undefined ? undefined : (value.adjustsVariable as Array<any>).map(VariableToJSON),
        'relevantForIntervention': value.relevantForIntervention === undefined ? undefined : (value.relevantForIntervention as Array<any>).map(InterventionToJSON),
        'position': value.position,
        'id': value.id,
        'usesUnit': value.usesUnit === undefined ? undefined : (value.usesUnit as Array<any>).map(UnitToJSON),
        'hasStepSize': value.hasStepSize,
    };
}


