// tslint:disable
/**
 * Model Catalog
 * This is the API of the Software Description Ontology at [https://w3id.org/okn/o/sdm](https://w3id.org/okn/o/sdm)
 *
 * The version of the OpenAPI document: v1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Class representing the characteristics of the code associated with a  software component
 * @export
 * @interface SourceCode
 */
export interface SourceCode {
    /**
     * License of a software component or its source code
     * @type {Array<string>}
     * @memberof SourceCode
     */
    license?: Array<string> | null;
    /**
     * Language used to code a software component
     * @type {Array<string>}
     * @memberof SourceCode
     */
    programmingLanguage?: Array<string> | null;
    /**
     * small description
     * @type {Array<string>}
     * @memberof SourceCode
     */
    description?: Array<string> | null;
    /**
     * URL to the code repository of a software component
     * @type {Array<string>}
     * @memberof SourceCode
     */
    codeRepository?: Array<string> | null;
    /**
     * identifier
     * @type {string}
     * @memberof SourceCode
     */
    id?: string;
    /**
     * short description of the resource
     * @type {Array<string>}
     * @memberof SourceCode
     */
    label?: Array<string> | null;
    /**
     * type of the resource
     * @type {Array<string>}
     * @memberof SourceCode
     */
    type?: Array<string> | null;
}

export function SourceCodeFromJSON(json: any): SourceCode {
    return SourceCodeFromJSONTyped(json, false);
}

export function SourceCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceCode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'license': !exists(json, 'license') ? undefined : json['license'],
        'programmingLanguage': !exists(json, 'programmingLanguage') ? undefined : json['programmingLanguage'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'codeRepository': !exists(json, 'codeRepository') ? undefined : json['codeRepository'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function SourceCodeToJSON(value?: SourceCode): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'license': value.license,
        'programmingLanguage': value.programmingLanguage,
        'description': value.description,
        'codeRepository': value.codeRepository,
        'id': value.id,
        'label': value.label,
        'type': value.type,
    };
}


