// tslint:disable
/**
 * Model Catalog
 * This is MINT Model Catalog You can find out more about Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpatiallyDistributedGrid
 */
export interface SpatiallyDistributedGrid {
    /**
     * 
     * @type {Array<number>}
     * @memberof SpatiallyDistributedGrid
     */
    hasDimensionality?: Array<number> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SpatiallyDistributedGrid
     */
    hasFormat?: Array<string> | null;
    /**
     * 
     * @type {object}
     * @memberof SpatiallyDistributedGrid
     */
    hasFileStructure?: object | null;
    /**
     * 
     * @type {Array<object>}
     * @memberof SpatiallyDistributedGrid
     */
    hasPresentation?: Array<object> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SpatiallyDistributedGrid
     */
    label?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SpatiallyDistributedGrid
     */
    type?: Array<string> | null;
    /**
     * 
     * @type {Array<object>}
     * @memberof SpatiallyDistributedGrid
     */
    hasFixedResource?: Array<object> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SpatiallyDistributedGrid
     */
    hasSpatialResolution?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SpatiallyDistributedGrid
     */
    hasCoordinateSystem?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SpatiallyDistributedGrid
     */
    hasShape?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SpatiallyDistributedGrid
     */
    hasDimension?: Array<string> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof SpatiallyDistributedGrid
     */
    position?: Array<number> | null;
    /**
     * 
     * @type {string}
     * @memberof SpatiallyDistributedGrid
     */
    id?: string;
}

export function SpatiallyDistributedGridFromJSON(json: any): SpatiallyDistributedGrid {
    return SpatiallyDistributedGridFromJSONTyped(json, false);
}

export function SpatiallyDistributedGridFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpatiallyDistributedGrid {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hasDimensionality': !exists(json, 'hasDimensionality') ? undefined : json['hasDimensionality'],
        'hasFormat': !exists(json, 'hasFormat') ? undefined : json['hasFormat'],
        'hasFileStructure': !exists(json, 'hasFileStructure') ? undefined : json['hasFileStructure'],
        'hasPresentation': !exists(json, 'hasPresentation') ? undefined : json['hasPresentation'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'hasFixedResource': !exists(json, 'hasFixedResource') ? undefined : json['hasFixedResource'],
        'hasSpatialResolution': !exists(json, 'hasSpatialResolution') ? undefined : json['hasSpatialResolution'],
        'hasCoordinateSystem': !exists(json, 'hasCoordinateSystem') ? undefined : json['hasCoordinateSystem'],
        'hasShape': !exists(json, 'hasShape') ? undefined : json['hasShape'],
        'hasDimension': !exists(json, 'hasDimension') ? undefined : json['hasDimension'],
        'position': !exists(json, 'position') ? undefined : json['position'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function SpatiallyDistributedGridToJSON(value?: SpatiallyDistributedGrid): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hasDimensionality': value.hasDimensionality,
        'hasFormat': value.hasFormat,
        'hasFileStructure': value.hasFileStructure,
        'hasPresentation': value.hasPresentation,
        'label': value.label,
        'type': value.type,
        'hasFixedResource': value.hasFixedResource,
        'hasSpatialResolution': value.hasSpatialResolution,
        'hasCoordinateSystem': value.hasCoordinateSystem,
        'hasShape': value.hasShape,
        'hasDimension': value.hasDimension,
        'position': value.position,
        'id': value.id,
    };
}


