// tslint:disable
/**
 * Model Catalog
 * This is the API of the Software Description Ontology at [https://w3id.org/okn/o/sdm](https://w3id.org/okn/o/sdm)
 *
 * The version of the OpenAPI document: v1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Unit,
    UnitFromJSON,
    UnitFromJSONTyped,
    UnitToJSON,
} from './';

/**
 * Time interval at which a model produces output. For example, a model may produce outputs for every simulated day, hour, etc.
 * @export
 * @interface TimeInterval
 */
export interface TimeInterval {
    /**
     * Unit used in an interval (e.g., month)
     * @type {Array<Unit>}
     * @memberof TimeInterval
     */
    intervalUnit?: Array<Unit> | null;
    /**
     * small description
     * @type {Array<string>}
     * @memberof TimeInterval
     */
    description?: Array<string> | null;
    /**
     * identifier
     * @type {string}
     * @memberof TimeInterval
     */
    id?: string;
    /**
     * short description of the resource
     * @type {Array<string>}
     * @memberof TimeInterval
     */
    label?: Array<string> | null;
    /**
     * type of the resource
     * @type {Array<string>}
     * @memberof TimeInterval
     */
    type?: Array<string> | null;
    /**
     * Value used in the time interval of a model (e.g., 1 month, 5 days, \'harvest cycle\')
     * @type {Array<Integer | string>}
     * @memberof TimeInterval
     */
    intervalValue?: Array<string> | null;
}

export function TimeIntervalFromJSON(json: any): TimeInterval {
    return TimeIntervalFromJSONTyped(json, false);
}

export function TimeIntervalFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeInterval {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'intervalUnit': !exists(json, 'intervalUnit') ? undefined : (json['intervalUnit'] as Array<any>).map(UnitFromJSON),
        'description': !exists(json, 'description') ? undefined : json['description'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'intervalValue': !exists(json, 'intervalValue') ? undefined : json['intervalValue'],
    };
}

export function TimeIntervalToJSON(value?: TimeInterval): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'intervalUnit': value.intervalUnit === undefined ? undefined : (value.intervalUnit as Array<any>).map(UnitToJSON),
        'description': value.description,
        'id': value.id,
        'label': value.label,
        'type': value.type,
        'intervalValue': value.intervalValue,
    };
}


